name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy files to S3
        run: |
          aws s3 sync . s3://abbystevenson.co.uk --delete --exact-timestamps --exclude ".git/*" --exclude ".github/*"

      - name: Get list of changed files
        id: changed
        run: |
          echo "CHANGED_PATHS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.html$|\.css$|\.js$|\.png$|\.jpg$|\.svg$' | sed 's|^|/|' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Invalidate changed files in CloudFront
        if: env.CHANGED_PATHS != ''
        run: |
          echo "Invalidating: $CHANGED_PATHS"
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths $CHANGED_PATHS
